package com.apprenova.renovacheck.navigation

object Route {
    const val SPLASH      = "splash"
    const val WELCOME     = "welcome"
    const val ONBOARDING  = "onboarding"
    const val DASHBOARD   = "dashboard"
    const val PROJECTS    = "projects"
    const val ADD_PROJECT = "add_project"
    const val PROJECT_DETAIL = "project_detail/{projectId}"
    const val ROOMS       = "rooms/{projectId}"
    const val ADD_ROOM    = "add_room/{projectId}"
    const val ROOM_DETAIL = "room_detail/{roomId}"
    const val CHECKLISTS  = "checklists"
    const val CHECKLIST_DETAIL = "checklist_detail/{checklistId}"
    const val CUSTOM_CHECKLIST = "custom_checklist"
    const val INSPECTION  = "inspection/{roomId}/{checklistId}"
    const val INSPECTION_RESULT = "inspection_result/{inspectionId}"
    const val ADD_ISSUE   = "add_issue/{projectId}"
    const val ISSUES      = "issues/{projectId}"
    const val ISSUE_DETAIL = "issue_detail/{issueId}"
    const val PHOTOS      = "photos/{projectId}"
    const val BEFORE_AFTER = "before_after/{projectId}"
    const val ROOM_SCORE  = "room_score/{roomId}"
    const val REPORTS     = "reports/{projectId}"
    const val CONTRACTOR_NOTES = "contractor_notes/{projectId}"
    const val TIMELINE    = "timeline/{projectId}"
    const val TASKS       = "tasks/{projectId}"
    const val NOTIFICATIONS = "notifications"
    const val ACTIVITY    = "activity"
    const val PROFILE     = "profile"
    const val SETTINGS    = "settings"

    fun projectDetail(id: String) = "project_detail/$id"
    fun rooms(projectId: String) = "rooms/$projectId"
    fun addRoom(projectId: String) = "add_room/$projectId"
    fun roomDetail(roomId: String) = "room_detail/$roomId"
    fun checklistDetail(id: String) = "checklist_detail/$id"
    fun inspection(roomId: String, checklistId: String) = "inspection/$roomId/$checklistId"
    fun inspectionResult(id: String) = "inspection_result/$id"
    fun addIssue(projectId: String) = "add_issue/$projectId"
    fun issues(projectId: String) = "issues/$projectId"
    fun issueDetail(id: String) = "issue_detail/$id"
    fun photos(projectId: String) = "photos/$projectId"
    fun beforeAfter(projectId: String) = "before_after/$projectId"
    fun roomScore(roomId: String) = "room_score/$roomId"
    fun reports(projectId: String) = "reports/$projectId"
    fun contractorNotes(projectId: String) = "contractor_notes/$projectId"
    fun timeline(projectId: String) = "timeline/$projectId"
    fun tasks(projectId: String) = "tasks/$projectId"
}
